name: release
on:
  push:
    branches: [main]
jobs:
  tag-and-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Read version
        id: v
        run: |
          set -euo pipefail
          VERSION=$(grep -Eo '"version": *"[^"]+"' package.json 2>/dev/null | cut -d\" -f4 || true)
          [[ -z "$VERSION" ]] && VERSION=$(grep -E '^version *= *' pyproject.toml 2>/dev/null | sed 's/.*= *//;s/"//g' || true)
          [[ -z "$VERSION" ]] && VERSION=$(grep -E '^version *= *' Cargo.toml 2>/dev/null | head -1 | sed 's/.*= *//;s/"//g' || true)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Create tag if missing
        run: |
          [[ -z "${{ steps.v.outputs.version }}" ]] && { echo "No version parsed"; exit 1; }
          TAG="v${{ steps.v.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
          else
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi
      - name: Generate release notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.v.outputs.version }}
          body_path: .github/RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
